workflows:
  patrol_test:
    name: Patrol Test Workflow
    max_build_duration: 60
    instance_type: linux
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install Patrol CLI
        script: dart pub global activate patrol_cli

      - name: List Emulators
        script: emulator -list-avds
          
      - name: SDK manager
        script: |
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools 
          sdkmanager --update
          yes | sdkmanager --licenses

      - name: Launch emulator
        script: |
           cd $ANDROID_HOME/tools
           emulator -avd emulator & 
           adb wait-for-device
      
      - name: Run tests with Patrol
        script: patrol test -t integration_test/e2e_test.dart
        ignore_failure: true

    artifacts:
      # Collect Patrol test reports
      - ./patrol/reports/**/*
