workflows:
  patrol_test:
    name: Patrol Test Workflow
    environment:
      flutter: stable
      xcode: latest
      vars:
        ANDROID_HOME: $HOME/Library/Android/sdk
        ANDROID_SDK_ROOT: /opt/android-sdk
        PATH: $PATH:/opt/android-sdk/cmdline-tools/latest/bin:/opt/android-sdk/platform-tools:/opt/android-sdk/emulator
    scripts:
      # 1. Install Flutter dependencies
      - name: Install Flutter dependencies
        script: |
          flutter pub get
          
      # 2. Set up Android SDK Command-Line Tools
      - name: Set up Android SDK
        script: |
          mkdir -p $ANDROID_HOME/cmdline-tools
          curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-mac-9477386_latest.zip
          unzip sdk-tools.zip -d $ANDROID_HOME/cmdline-tools
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          rm sdk-tools.zip

      - name: Debug PATH and SDK Tools
        script: |
          echo "PATH: $PATH"
          which sdkmanager || echo "sdkmanager not found"
          ls -l $ANDROID_HOME/cmdline-tools/latest/bin || echo "SDK Tools directory not found"

      - name: Install Android SDK Command-Line Tools
        script: |
          sdkmanager --install "cmdline-tools;latest"
          sdkmanager --install "platform-tools"
          sdkmanager --install "emulator"
          sdkmanager --install "system-images;android-30;google_apis;x86_64"
          sdkmanager --licenses
      
      - name: Install Android SDK Components
        script: |
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "emulator" "system-images;android-30;google_apis;x86_64"
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Debug AVD setup
        script: |
          sdkmanager --list
          avdmanager list device
          avdmanager list avd
          echo "AVD files:"
          ls -l $HOME/.android/avd
          
      # 3. Create Android Virtual Device (AVD)
      - name: Set up Android emulator
        script: |
          eecho "no" | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n patrol_test_avd -k "system-images;android-30;google_apis;x86_64" --device "pixel_3a"
          $ANDROID_HOME/emulator/emulator -avd patrol_test_avd -no-window -no-audio -no-snapshot &
          adb wait-for-device
          adb shell input keyevent 82 # Unlock screen
          
    artifacts:
      # Collect Patrol test reports
      - ./patrol/reports/**/*
