definitions:
  qa_emails: &qa_emails
    - baloabby@gmail.com
  
  artifacts: &artifacts
    - patrol-results/**/*.png
    - patrol-results/**/*.xml
    - patrol-results/**/*.mp4
    - test_report/**/*.xml 

  max_build_duration: &duration 120

  env_settings: &env_settings
    flutter: 3.24.3
    xcode: latest
    cocoapods: default

  scripts:
    - &install_flutter_dependencies
      name: Get Flutter dependencies
      script: |
        flutter clean
        flutter pub get

    - &install_patrol_cli
      name: Install Patrol CLI
      script: |
        dart pub global activate patrol_cli 3.4.0

    - &android_setup_emulator
      name: Setup Android Emulator
      script: |
        # Setup SDK
        export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
        sdkmanager --update
        yes | sdkmanager --licenses
        
        # Create and launch emulator
        cd $ANDROID_HOME/tools
        emulator -avd emulator-34 &
        adb wait-for-device
        adb shell input keyevent 82

    - &android_patrol_test
      name: Run Android Patrol Tests
      script: |
        patrol test -t integration_test/fail_login_test.dart \
          --verbose
      ignore_failure: false

    - &ios_setup
      name: Setup iOS Environment
      script: |
        cd ios
        pod repo update
        pod install
        cd ..

    - &ios_simulator_setup
      name: Start iOS Simulator
      script: |
        xcrun simctl boot "iPhone 15"

    - &ios_patrol_test
      name: Run iOS Patrol Tests
      script: |
        patrol test -t integration_test/fail_login_test.dart  \
          -d "iPhone 15" \
          --verbose > reports/test_report.xml

    - &generate_test_report
      name: Generate Test Report
      script: |
        mkdir -p reports
        if [ ! -f reports/test_report.xml ]; then
        echo "Test report not found. Skipping email sending."
        exit 1
        fi
        echo "Test report generated at reports/test_report.xml"

    - &send_test_results_email
      name: Email Test Results
      script: |
        echo "Sending test results to QA team..."
        # Encode the test report to base64
        base64 reports/test_report.xml > reports/test_report.base64
        (
          echo "Subject: Test Results: Patrol Tests"
          echo "To: ${qa_emails[@]}"
          echo "MIME-Version: 1.0"
          echo "Content-Type: multipart/mixed; boundary=\"boundary123\""
          echo ""
          echo "--boundary123"
          echo "Content-Type: text/plain; charset=\"UTF-8\""
          echo ""
          echo "Test results are attached."
          echo ""
          echo "--boundary123"
          echo "Content-Type: application/xml; name=\"test_report.xml\""
          echo "Content-Disposition: attachment; filename=\"test_report.xml\""
          echo "Content-Transfer-Encoding: base64"
          cat reports/test_report.base64
          echo "--boundary123--"
        )

workflows:
  patrol_android_test:
    name: Android Test Workflow
    max_build_duration: *duration
    instance_type: linux
    environment:
      <<: *env_settings
    scripts:
      - *install_flutter_dependencies
      - *install_patrol_cli
      - *android_setup_emulator
      - *android_patrol_test
      - *generate_test_report
      - *send_test_results_email 
    artifacts: *artifacts
    publishing:
      email:
        recipients: *qa_emails

  patrol_ios_test:
    name: iOS Test Workflow
    instance_type: mac_mini_m2
    max_build_duration: *duration
    environment:
      <<: *env_settings
    scripts:
      - *install_flutter_dependencies
      - *install_patrol_cli
      - *ios_setup
      - *ios_simulator_setup
      - *ios_patrol_test
      - *generate_test_report
      - *send_test_results_email 
    artifacts: *artifacts
    publishing:
      email:
        recipients: *qa_emails
