workflows:
  patrol_test:
    name: Patrol Test Workflow
    instance_type: linux_x2
    environment:
      flutter: stable
      xcode: latest
      java: 11
      vars:
        ANDROID_HOME: $HOME/Library/Android/sdk
        ANDROID_SDK_ROOT: /opt/android-sdk
        PATH: $PATH:/opt/android-sdk/cmdline-tools/latest/bin:/opt/android-sdk/platform-tools:/opt/android-sdk/emulator
    scripts:
      # 1. Install Flutter dependencies
      - name: Install Flutter dependencies
        script: |
          flutter pub get
          
      # 2. Set up Android SDK Command-Line Tools
      - name: Set up Android SDK
        script: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O commandlinetools.zip
          unzip commandlinetools.zip -d $HOME/android-sdk
          rm commandlinetools.zip
          echo "export ANDROID_HOME=$HOME/android-sdk" >> $BASH_ENV
          echo "export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH" >> $BASH_ENV
          source $BASH_ENV
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-30" "emulator" "system-images;android-30;google_apis;x86_64"

      - name: Debug PATH and SDK Tools
        script: |
          echo "PATH: $PATH"
          which sdkmanager || echo "sdkmanager not found"
          ls -l $ANDROID_HOME/cmdline-tools/latest/bin || echo "SDK Tools directory not found"
      
      - name: Install Android SDK Components
        script: |
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "system-images;android-30;google_apis_playstore;arm64-v8a"
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Launch Android emulator
        script: |
          cd $ANDROID_HOME/tools
          emulator -avd emulator &
          adb wait-for-device      

      - name: Install Patrol CLI
        script: dart pub global activate patrol_cli

      - name: Run tests with Patrol
        script: patrol test -t integration_test/e2e_test.dart
        ignore_failure: true

    artifacts:
      # Collect Patrol test reports
      - ./patrol/reports/**/*
