workflows:
  patrol-ios-integration-tests:
    name: iOS Patrol Integration Tests
    environment:
      flutter: 3.24.3
      xcode: 16.1 
      cocoapods: 1.14.3 
    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - $HOME/.pub-cache
    scripts:
      # Prepare environment
      - flutter clean
      - flutter pub get
      
      # Install Patrol CLI
      - dart pub global activate patrol_cli
      - dart pub global run patrol:bootstrap
      
      # Prepare simulators
      - xcrun simctl create patrol-test-device "iPhone 15 Pro" com.apple.CoreSimulator.SimRuntime.iOS-16-4
      
      # Run Patrol tests
      - patrol test integration_test/ -d patrol-test-device
    
    artifacts:
      - flutter_drive.log
      - build/app/outputs/flutter-apk/*.apk
    
    publishing:
      email:
        recipients:
          - baloabby@gmail.com

  patrol-android-integration-tests:
    name: Android Patrol Integration Tests
    environment:
      flutter: 3.24.3
    cache:
      cache_paths:
        - $HOME/.gradle
        - $HOME/.pub-cache
    scripts:
    # Prepare environment
      - flutter clean
      - flutter pub get

    # Install Patrol CLI
      - dart pub add --dev patrol
      - dart pub global activate patrol_cli


      - mkdir -p $ANDROID_HOME/cmdline-tools
      - curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-mac-7583922_latest.zip
      - unzip -q commandlinetools.zip -d $ANDROID_HOME/cmdline-tools
      - mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest

    
    # Install Patrol CLI
      - cd $ANDROID_HOME/tools
      - emulator -avd emulator &
      - adb wait-for-device     


    # Ensure Android SDK tools are available
      - yes | sdkmanager --licenses
      - sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"
      - sdkmanager "system-images;android-30;google_apis;x86_64"
      
      # Android SDK and emulator setup
      - echo "no" | avdmanager create avd -n test-emulator -k "system-images;android-30;google_apis;x86_64"
      - emulator -avd test-emulator -no-window -no-audio &
      

      # Wait for emulator
      - android-wait-for-emulator
      
      # Run Patrol tests
      - patrol test -t integration_test
      
    
    artifacts:
      - flutter_drive.log
      - build/app/outputs/flutter-apk/*.apk
    
    publishing:
      email:
        recipients:
          - baloabby@gmail.com